spring.application.name=lending-service

spring.datasource.url=jdbc:postgresql://localhost:5432/lending_service
spring.datasource.username=postgres
spring.datasource.password=970523
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

app.library.policy.max-active-loans-per-member=3
app.library.policy.loan-duration-days=14
app.library.policy.max-renewals=2
app.library.policy.fine-per-day-cents=25
app.library.policy.max-outstanding-fines=10


spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=build/generated-schema.sql
spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
spring.jpa.properties.hibernate.format_sql=true
